### ISSUE TITLE
move berry icon in front of input node to the left side

### ISSUE THREAD

**Issue by iamhermes** [UniPiTechnology/node-red-contrib-unipi-evok#1]
At first glance, it is not possible to distinguish the input node from the output node.
Please move the unipi berry in the input node to the left side.

![grafik](https://user-images.githubusercontent.com/4535068/53985947-31fc8300-411d-11e9-8518-dc08bc301831.png)

**Comment by Krivik** [comment]
Hi, that is a great idea. We are about to release new version where some details will be fixed. I'm gonna move the icon.

**Comment by Krivik** [comment]
Icon was moved.
